language: rust

rust:
    - nightly

sudo: false

script:
    - cargo build --verbose && cargo doc --verbose

after_success:
    - |
        [ $TRAVIS_RUST_VERSION = nightly ] &&
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        echo '<meta http-equiv=refresh content=0;url=chromaprint/index.html>' > target/doc/index.html &&
        git clone https://github.com/davisp/ghp-import &&
        ./ghp-import/ghp-import -n target/doc &&
        git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

env:
    global:
        secure: c8xquwMIMG22TC0r65kS52x6G+eow6BODAIZuPkfc4z0kCkY3P4Gvf7fLRgdTVp4Z8TGU6DcuaTizpkjFwmMytdwjuKiaAxU0TxN6jH4uJSVTXiA6bwWkvrz1YykXi2g1+R7+FwlKdJyMWq576fP+qB8ZpAMoXguVBt7k1hmYcc=
